name: Playwright Tests

on:
  workflow_dispatch:
permissions: # Required when using Microsoft Entra ID to authenticate
    id-token: write
    contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production # for Entra as mentioned in user managed identity setup
    defaults:
      run:
        working-directory: samples/playwright-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # GitHub Open ID connect values copied in previous steps
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.service.config.ts
        env:
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
          PLAYWRIGHT_SERVICE_AUTH_TYPE: ENTRA_ID
          # PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }} # Not recommended, use Microsoft Entra ID authentication. 

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: samples/playwright-tests/playwright-report
          retention-days: 10